name: build

on:
  pull_request:
  push:

jobs:
  build-project:
 #   strategy:
 #     matrix:
 #       os: [ubuntu-latest, macos-latest, windows-latest]
 #   runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Bheckout branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build -x test
          gradle-version: 6.4.1
