name: Deploy to docker hub

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build bootable Jar
        run: ./gradlew bootJar
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build latest image
        run: docker build -t ${GITHUB_REPOSITORY}:latest .

      - name: Push to docker registry
        run: docker push ${GITHUB_REPOSITORY}:latest