name: Deploy to DockerHub

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build bootable Jar
        run: ./gradlew bootJar
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: s1810/backend
          tags: latest