# On every push we check if the current branch is able to be built

name: Test Project And Report Code Coverage

on: pull_request

jobs:
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Danger
        uses: danger/kotlin@0.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_KEY }}
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Lint Kotlin with Gradle
        run: ./gradlew lintKotlin
      - name: Build with Gradle
        run: ./gradlew test
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: github-backend
          SLACK_COLOR: '#3278BD'